### ISSUE TITLE
Отсутствует информация о том, кто предложил трек

### ISSUE THREAD

**Issue by polarbearjngl** [LimaSoulMusic/TheJammersBeta#12]
**Опишите ошибку**
Отсутствует информация о том, ктопредложил трек в список

**Как воспроизвести**
Шаги для воспроизведения поведения:
1. Добавить трек или пройтись по трекам добавленным другими юзерами и определить кто его добавил

**Ожидаемое поведение**
Можно понять кто добавил трек, иметь возможность открыть его профил и узнать там его ник в телеграм и написать ему

**Смартфон (пожалуйста, заполните следующую информацию):**
NA

**Comment by samokryl** [comment]
resolved https://github.com/LimaSoulMusic/LimaSoulMusic/pull/190

**Comment by samokryl** [comment]
<img width="281" alt="Screenshot 2024-10-27 at 10 03 32 PM" src="https://github.com/user-attachments/assets/b7135542-85bf-4eca-974b-a3e69bfe003c">
