### ISSUE TITLE
Неполное\некорректное отображение инструментов на экране со списком треков в ивенте

### ISSUE THREAD

**Issue by polarbearjngl** [LimaSoulMusic/TheJammersBeta#13]
**Опишите ошибку**
Неполное\некорректное отображение инструментов на экране со списком треков в ивенте. Мне как юзеру непонятно что означают серые иконки инструментов, почему их только 2, хотя в самом треке их 7

**Как воспроизвести**
Шаги для воспроизведения поведения:
1. Перейдите к треку с большим кол-вом инструментов, например 7
2. Заполните все инструменты музыкантами, чтобы трек был собран
3. Перейдите на страницу со списком треков эвента
4. Отображение инструментов не отражает то какие инструменты нужны\не нужны в треке

**Ожидаемое поведение**
Отображение инструментов отражает то какие инструменты нужны\не нужны в треке

**Скриншоты**
Список вписавшихся в трек, когда собраны все инструменты
![image](https://github.com/user-attachments/assets/b53e1f87-5f41-4cf0-b7b7-95bd3af0cde3)
Список всех треков эвента, когда собраны все инструменты
![image](https://github.com/user-attachments/assets/7d19fa56-c608-4009-a11c-5271a3454c73)

Список вписавшихся в трек, когда собраны НЕ все инструменты
![image](https://github.com/user-attachments/assets/b8dec603-c91a-46a5-8df4-7cb421e68191)
Список всех треков эвента, когда собраны НЕ все инструменты
![image](https://github.com/user-attachments/assets/6aed7e32-37b4-49b3-9ad5-39307247df93)

**Смартфон (пожалуйста, заполните следующую информацию):**
 - Samsung galaxy s23
 - Android 14

**Comment by samokryl** [comment]
Изначально на экране со списокм были все инструменты, но передумали и оставили только те, которые требуются.
Надо ещё раз обсудить ux на этом экране.

**Comment by samokryl** [comment]
Оставляем без изменений.
