### ISSUE TITLE
Необходима возможность сделать инструмент в треке опциональным

### ISSUE THREAD

**Issue by polarbearjngl** [LimaSoulMusic/TheJammersBeta#16]
**Связан ли ваш запрос с проблемой? Пожалуйста, опишите.**
Необходима возможность сделать инструмент в треке опциональным. Тогда наличие его в треке не будет влиять на статус готовности трека

**Опишите решение, которое вы хотели бы получить**
возможность сделать инструмент в треке опциональным. Но при этом нужно чтобы в списке всех треков было видно что хотя трек и собран, но в нем еще есть место для опционального инструмента. Например 2 гитары, одна из которых не обязательна. Или клавиши вместо которых будет плейбек

**Comment by samokryl** [comment]
Согласен. Мы осознано не тащили этот функционал в бету.
Можно оставить до следующей итерации.
И если делать, то на основе изменений из #4

**Comment by samokryl** [comment]
Решение в #4
