### ISSUE TITLE
Socket timeout has expired

### ISSUE THREAD

**Issue by frussian** [LimaSoulMusic/TheJammersBeta#6]
**Опишите ошибку**
Часто получаю таймауты при выходе из страницы с треком на страницу с общим списком песен ивента. Используется мобильный интернет.

**Как воспроизвести**
Шаги для воспроизведения поведения:
1. Зайти на страницу с песней
2. Вернуться со страницы с песней на страницу с ивентом
3. Просмотреть сообщение об ошибке

**Ожидаемое поведение**
Ожидаю загрузку списка песен ивента вместо ошибки

**Скриншоты**
![photo_2024-10-26_14-24-06](https://github.com/user-attachments/assets/8250b12d-3226-43f5-93c3-18f7509f05a8)

**Смартфон (пожалуйста, заполните следующую информацию):**
 - Устройство: Xiaomi 14
 - Операционная система: HyperOS, Android 14

**Дополнительный контекст**
Возможно как-то связано с #3, хотя та ошибка при использовании WiFi, а здесь мобильный интернет.

**Comment by samokryl** [comment]
Посмотреть firebase-аналитику. Может там есть подробности по проблеме.
Можно увеличить таймауты на клиенте.
Надо настроить мониторинг в графане с алёртингом на возникающие проблемы с сетью.

**Comment by frussian** [comment]
в другой WiFi сети все работает нормально
