### ISSUE TITLE
Добавить возможность посмотреть телеграм ники тех кто вписан в трек

### ISSUE THREAD

**Issue by polarbearjngl** [LimaSoulMusic/TheJammersBeta#9]
**Связан ли ваш запрос с проблемой? Пожалуйста, опишите.**
Нужно чтобы пользователь имел возможность увидеть телеграм ники тех кто вписан в трек. Фича редактирования профиля есть, в ней есть обязательное поле "Telegram", но оно пока никак не используется

**Опишите решение, которое вы хотели бы получить**

- возможность увидеть телеграм ники тех кто вписан в песню

**Опишите альтернативы, которые вы рассматривали**
- возможность кликнуть по телеграм никам чтобы сразу перейти в телеграм, в собщения этому человеку

**Comment by samokryl** [comment]
resolved https://github.com/LimaSoulMusic/LimaSoulMusic/pull/190
